<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllOrderedByDateAdd($page, $nbPerPage)
  {
    $query = $this->createQueryBuilder('p')->orderBy('p.dateAdd', 'ASC')->getQuery();
    $query->setFirstResult(($page-1) * $nbPerPage)->setMaxResults($nbPerPage);
    return new Paginator($query, true);
  }
}
