<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllOrderedByDateAdd($page, $nbPerPage)
    {
      $query = $this->createQueryBuilder('p')->where('p.published = true')->orderBy('p.dateAdd', 'DESC')->getQuery();
      $query->setFirstResult(($page-1) * $nbPerPage)->setMaxResults($nbPerPage);
      return new Paginator($query, true);
    }

}
